### ISSUE TITLE
Rename to CommandKit

### ISSUE THREAD

**Issue by kylef** [kylef/CommandKit#9]
Unfortunately there is a pod called [CLIKit](https://cocoapods.org/pods/CLIKit) so I'm prosing a rename (to CommandKit).

@radex any thoughts on this?

**Comment by radex** [comment]
Bummed that we didn't get the pod name, since it looks like we were first and I liked it :/ CommandKit sounds pretty good, too.

**Comment by schickling** [comment]
+1 for the name!

**Comment by fpg1503** [comment]
+1
